Disable tests trying to look up remote servers.

diff --git a/test/test_credentials.py b/test/test_credentials.py
--- a/test/test_credentials.py
+++ b/test/test_credentials.py
@@ -68,6 +68,7 @@ class CredentialCreateTest(utils.NoRepoTestCase):
         self.assertEqual((username, None, None, None), cred.credential_tuple)
 
 
+@unittest.skipIf(True, "network tests are not supported in Guix")
 class CredentialCallback(utils.RepoTestCase):
     def test_callback(self):
         class MyCallbacks(pygit2.RemoteCallbacks):
@@ -92,6 +93,7 @@ class CredentialCallback(utils.RepoTestCase):
         remote = self.repo.create_remote("github", url)
         self.assertRaises(TypeError, lambda: remote.fetch(callbacks=MyCallbacks()))
 
+@unittest.skipIf(True, "network tests are not supported in Guix")
 class CallableCredentialTest(utils.RepoTestCase):
 
     def test_user_pass(self):
diff --git a/test/test_repository.py b/test/test_repository.py
--- a/test/test_repository.py
+++ b/test/test_repository.py
@@ -573,6 +573,7 @@ class CloneRepositoryTest(utils.NoRepoTestCase):
         self.assertTrue('refs/remotes/custom_remote/master' in repo.listall_references())
         self.assertIsNotNone(repo.remotes["custom_remote"])
 
+    @unittest.skipIf(True, "network tests are not supported in Guix")
     def test_clone_with_credentials(self):
         repo = clone_repository(
             "https://bitbucket.org/libgit2/testgitrepository.git",
diff --git a/test/test_submodule.py b/test/test_submodule.py
--- a/test/test_submodule.py
+++ b/test/test_submodule.py
@@ -42,6 +42,7 @@ SUBM_PATH = 'submodule'
 SUBM_URL = 'https://github.com/libgit2/pygit2'
 SUBM_HEAD_SHA = '819cbff552e46ac4b8d10925cc422a30aa04e78e'
 
+@unittest.skipIf(True, "network tests are not supported in Guix")
 class SubmoduleTest(utils.SubmoduleRepoTestCase):
 
     def test_lookup_submodule(self):
